/* This file was generated by the Hex-Rays decompiler version 9.3.0.260327.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
// __int64 thrd_yield(void); weak
// int _cxa_finalize(void *);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)());
char *sub_1090();
__int64 sub_10C0();
char *sub_1100();
__int64 sub_1140();
void sub_1150();
int main(int, char **, char **); // idb
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// int __cxa_finalize(void *);
// __int64 ITM_deregisterTMCloneTable(void); weak
// __int64 _gmon_start__(void); weak
// __int64 ITM_registerTMCloneTable(void); weak

//-------------------------------------------------------------------------
// Data declarations

void *off_4018 = &off_4018; // idb
char byte_4020; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 4050: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001060) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)())
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main(main, v4, &retaddr, nullptr, nullptr, a3, &v5);
  __halt();
}
// 106A: positive sp value 8 has been found
// 1071: variable 'v3' is possibly undefined

//----- (0000000000001090) ----------------------------------------------------
char *sub_1090()
{
  return &byte_4020;
}
// 4020: using guessed type char byte_4020;
// 4048: using guessed type __int64 ITM_deregisterTMCloneTable(void);

//----- (00000000000010C0) ----------------------------------------------------
__int64 sub_10C0()
{
  return 0;
}
// 4058: using guessed type __int64 ITM_registerTMCloneTable(void);

//----- (0000000000001100) ----------------------------------------------------
char *sub_1100()
{
  char *result; // rax

  if ( !byte_4020 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(off_4018);
    result = sub_1090();
    byte_4020 = 1;
  }
  return result;
}
// 4020: using guessed type char byte_4020;

//----- (0000000000001140) ----------------------------------------------------
// attributes: thunk
__int64 sub_1140()
{
  return sub_10C0();
}

//----- (0000000000001150) ----------------------------------------------------
void sub_1150()
{
  thrd_yield();
}
// 1040: using guessed type __int64 thrd_yield(void);

//----- (00000000000014C8) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=19 queued=9 decompiled=9 lumina nreq=0 worse=0 better=0
// ALL OK, 9 function(s) have been successfully decompiled
