/* This file was generated by the Hex-Rays decompiler version 9.3.0.260327.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
// int printf(const char *format, ...);
// int _cxa_finalize(void *);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)());
char *sub_1080();
__int64 sub_10B0();
char *sub_10F0();
__int64 sub_1130();
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// int __cxa_finalize(void *);
// __int64 ITM_deregisterTMCloneTable(void); weak
// __int64 _gmon_start__(void); weak
// __int64 ITM_registerTMCloneTable(void); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN main;
_UNKNOWN unk_2010; // weak
void *off_4010 = &off_4010; // idb
char byte_4018; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 4040: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001050) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)())
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, nullptr, nullptr, a3, &v5);
  __halt();
}
// 105A: positive sp value 8 has been found
// 1061: variable 'v3' is possibly undefined

//----- (0000000000001080) ----------------------------------------------------
char *sub_1080()
{
  return &byte_4018;
}
// 4018: using guessed type char byte_4018;
// 4038: using guessed type __int64 ITM_deregisterTMCloneTable(void);

//----- (00000000000010B0) ----------------------------------------------------
__int64 sub_10B0()
{
  return 0;
}
// 4048: using guessed type __int64 ITM_registerTMCloneTable(void);

//----- (00000000000010F0) ----------------------------------------------------
char *sub_10F0()
{
  char *result; // rax

  if ( !byte_4018 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(off_4010);
    result = sub_1080();
    byte_4018 = 1;
  }
  return result;
}
// 4018: using guessed type char byte_4018;

//----- (0000000000001130) ----------------------------------------------------
// attributes: thunk
__int64 sub_1130()
{
  return sub_10B0();
}

//----- (00000000000012C0) ----------------------------------------------------
__int64 __fastcall main(int a1, char **a2, char **a3)
{
  int v3; // ecx
  _DWORD *v4; // rdx
  __int64 v5; // rdi
  int v6; // esi
  int v7; // eax
  int v8; // r10d
  int v9; // r11d
  int v10; // r9d
  unsigned int v11; // r9d
  unsigned int v12; // r9d
  __int64 v13; // r9
  int v14; // r10d
  unsigned int v15; // r10d
  int v16; // r9d
  int v17; // esi
  int v18; // ebx

  v3 = 0;
  v4 = &unk_2010;
  v5 = 0;
  v6 = 0;
  v7 = 0;
  do
  {
    v8 = (*v4 ^ 0x193) + 7;
    if ( ((*(_BYTE *)v4 ^ 0x93) & 1) != 0 )
      v8 = (*v4 ^ 0x193) - 3;
    v9 = -v8;
    v10 = v8;
    if ( v8 <= 0 )
      v10 = -v8;
    if ( !*v4 )
    {
      v7 += 3;
      goto LABEL_3;
    }
    if ( (unsigned int)(-858993459 * v10) > 0x33333333 )
    {
      if ( (unsigned int)(-1431655765 * v10) <= 0x55555555 )
      {
        if ( v9 > (__int64)v8 )
          v8 = -v8;
        v14 = v3 + v8;
        if ( v14 >= 101 )
          goto LABEL_23;
        v11 = v10 - v5 - v5;
        if ( v14 <= -51 )
        {
          v12 = v11 + 25;
          goto LABEL_27;
        }
      }
      else
      {
        v11 = (v5 + 11) ^ v10;
        if ( v11 >= 0x65 )
        {
          v12 = v11 >> 1;
LABEL_27:
          v15 = v12;
          goto LABEL_28;
        }
      }
      v12 = v11 + 1;
      goto LABEL_27;
    }
    v13 = v8;
    if ( v9 > (__int64)v8 )
      v8 = -v8;
    v14 = v5 + v8;
    if ( (unsigned int)v14 >= 0x65 )
    {
LABEL_23:
      v15 = (unsigned int)v14 >> 1;
      goto LABEL_28;
    }
    if ( v9 > v13 )
      LODWORD(v13) = v9;
    v15 = v13 + v5 + 1;
LABEL_28:
    v6 += v15;
    v16 = v5;
    if ( (v6 & 1) != 0 )
      v16 = *v4 & 3;
    v7 += v16;
    if ( v6 > 500 )
    {
      if ( (_DWORD)v5 == 10 )
        v7 = -v7;
      v17 = v7 + v6;
      if ( v17 < 0 )
        goto LABEL_36;
      goto LABEL_31;
    }
LABEL_3:
    ++v5;
    v3 -= 2;
    ++v4;
  }
  while ( v5 != 10 );
  v17 = v6 - v7;
  if ( v17 < 0 )
  {
LABEL_36:
    v18 = -1;
    goto LABEL_37;
  }
LABEL_31:
  v18 = 0;
  if ( (unsigned int)v17 >= 0x64 )
    v18 = (((unsigned int)v17 | 0x200000000uLL) - 300) >> 32;
LABEL_37:
  printf("score = %d\n", v17);
  printf("class = %d\n", v18);
  return 0;
}

//----- (000000000000144C) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=17 queued=9 decompiled=9 lumina nreq=0 worse=0 better=0
// ALL OK, 9 function(s) have been successfully decompiled
